#!/usr/bin/env python3
"""Record an INDEPENDENTLY-SOURCED reference corpus from NASA/JPL Horizons.

Why this exists
---------------
``tests/goldens/swiss_ephemeris_goldens.json`` is recorded by running this engine
and writing down what it said (``UPDATE_SWISS_GOLDENS=1``). That is a perfectly
good *regression* detector — it catches the engine's numbers moving — but it
cannot detect that the numbers were wrong on the day they were recorded, because
the expected value and the observed value come from the same code. A golden
generated by the code under test proves only self-consistency.

This corpus is different: every expected value is fetched from **NASA/JPL
Horizons**, an authority entirely outside this repository's dependency set. It is
the reference implementation of the solar-system ephemeris (DE441) that the Swiss
Ephemeris data files are themselves a compression of, evaluated on JPL's own
servers by JPL's own code. Agreement between the two is therefore evidence about
*this engine's pipeline* — body identity, the sidereal conversion, the ayanamsa,
the lunar-node model, the Julian-Day transport — and not merely evidence that the
engine is reproducible.

WHAT IS FETCHED, AND IN WHICH FRAME
-----------------------------------
1. ``tropical_apparent_longitude_deg`` — for the seven visible grahas, Horizons'
   ``QUANTITIES='31'`` (``ObsEcLon``) observer quantity: apparent geocentric
   ecliptic longitude referred to the ecliptic and equinox **of date**, centred on
   ``500@399`` (the geocentre). That is precisely the frame and the corrections
   (light-time, aberration, relativistic deflection, nutation) that
   ``swe.calc_ut(..., FLG_SWIEPH | FLG_SIDEREAL)`` produces before the ayanamsa is
   subtracted, so the comparison is like-for-like.

2. ``moon_osculating_node_j2000_deg`` — Horizons' ``EPHEM_TYPE='ELEMENTS'``
   ``OM`` (longitude of the ascending node) for the Moon (301) about the Earth
   (500@399), ``REF_PLANE='ECLIPTIC'``. Horizons reports osculating elements in the
   **ecliptic of J2000.0** and accepts only TDB for them, which is why each epoch
   carries a ``jd_tdb`` alongside its ``jd_ut``.

   This is the external pin on the **lunar node**, the graha with by far the worst
   model and ephemeris-source exposure (``CLAUDE.md``: up to 1.981465100 deg between
   the true and mean models). The engine's declared node
   (``bphs_core.utils.LUNAR_NODE_BODY``) is compared against it in the J2000 frame,
   where JPL publishes it, so no frame rotation of ours sits between the two values.
   ``tests/test_lunar_node_model.py`` separately proves the served chart uses that
   same declared body, so the two contracts together carry JPL's number all the way
   to what a caller receives.

WHAT IS NOT FETCHED
-------------------
The **ayanamsa** has no counterpart in Horizons: it is an astrological convention
(the Lahiri/Chitrapaksha sidereal zero point fixed by the Indian Calendar Reform
Committee), not an astronomical observable, and no solar-system ephemeris publishes
it. It is therefore recorded here as ``ayanamsa_deg`` with
``"source": "engine"`` and is explicitly NOT an independent expected value — see the
provenance block written into the corpus, and the test module's docstring for what
the corpus does and does not establish about it.

USAGE
-----
    python ci/fetch_reference_corpus.py            # re-record from Horizons
    python ci/fetch_reference_corpus.py --check    # fetch and diff, write nothing

Network access is required to RE-RECORD. The committed corpus is read offline by
``tests/test_independent_reference_corpus.py``; the test never calls the network.
"""
from __future__ import annotations

import argparse
import datetime
import json
import pathlib
import re
import sys
import urllib.parse
import urllib.request

HORIZONS_API = "https://ssd.jpl.nasa.gov/api/horizons.api"
GEOCENTRE = "500@399"

CORPUS_PATH = pathlib.Path(__file__).resolve().parent.parent / "tests" / "goldens" / "independent_reference_corpus.json"

# Horizons target ids. These are BODY CENTRES (199/299/499/599/699), never the
# system barycentres (1/2/4/5/6) — swisseph returns body centres, and mixing the
# two would inject a real, if small, offset for the outer planets.
HORIZONS_TARGET = {
    "Sun": "10",
    "Moon": "301",
    "Mercury": "199",
    "Venus": "299",
    "Mars": "499",
    "Jupiter": "599",
    "Saturn": "699",
}
MOON_TARGET = "301"

# The seven visible grahas. Rahu and Ketu are pinned by the node query instead:
# neither is a body Horizons knows, because neither is a body.
VISIBLE_GRAHAS = ("Sun", "Moon", "Mars", "Mercury", "Jupiter", "Venus", "Saturn")

# ---------------------------------------------------------------------------
# Epochs — synthetic and non-personal, every one chosen for a stated astronomical
# reason. No real birth data of any person appears here or may ever be added:
# the workspace rule is absolute (CLAUDE.md, "Determinism").
# ---------------------------------------------------------------------------
EPOCHS: tuple[dict, ...] = (
    {
        "id": "j2000_epoch",
        "utc": "2000-01-01T12:00:00Z",
        "why": "The standard reference epoch J2000.0. Frame conventions coincide "
               "here, so a frame error elsewhere shows up as a discrepancy that "
               "vanishes at this epoch.",
    },
    {
        "id": "sample_a_instant",
        "utc": "1950-06-15T00:30:00Z",
        "why": "The UT instant of tests/conftest.py SAMPLE_A (06:00:00 local at "
               "UTC+5:30), so this corpus and swiss_ephemeris_goldens.json describe "
               "the same instants from two different sources.",
    },
    {
        "id": "sample_b_instant",
        "utc": "1975-12-01T07:00:00Z",
        "why": "The UT instant of tests/conftest.py SAMPLE_B (12:30:00 local at "
               "UTC+5:30).",
    },
    {
        "id": "sample_c_instant",
        "utc": "2000-03-21T03:30:00Z",
        "why": "The UT instant of tests/conftest.py SAMPLE_C (09:00:00 local at "
               "UTC+5:30).",
    },
    {
        "id": "node_model_divergence_extreme",
        "utc": "1905-10-10T22:00:00Z",
        "why": "CLAUDE.md's measured worst-case instant for the true-vs-mean lunar "
               "node divergence over the supported span (1.981465100 deg). Pinning "
               "the node HERE is what makes the corpus able to tell the two models "
               "apart; at a typical epoch they are close enough to be confused.",
    },
    {
        "id": "ephemeris_source_divergence_extreme",
        "utc": "1936-10-30T12:00:00Z",
        "why": "CLAUDE.md's measured worst-case instant for Swiss-vs-Moshier "
               "divergence on the true node (0.018175452 deg = 65.4316 arcsec) — the "
               "epoch where running on the fallback engine is most visible.",
    },
)


def _julian_day_ut(timestamp: str) -> float:
    """Julian Day of a UTC timestamp, by the standard civil-calendar algorithm.

    Deliberately NOT swisseph's ``swe.julday``: the epoch definition must not come
    from the library under test. This is the textbook Fliegel/Van Flandern-style
    conversion (Meeus, *Astronomical Algorithms*, ch. 7) and is checked against a
    known value by ci/tests/test_reference_corpus_fetcher.py.
    """
    moment = datetime.datetime.fromisoformat(timestamp.replace("Z", "+00:00"))
    year, month = moment.year, moment.month
    day = (
        moment.day
        + moment.hour / 24.0
        + moment.minute / 1440.0
        + moment.second / 86400.0
    )
    if month <= 2:
        year -= 1
        month += 12
    a = year // 100
    b = 2 - a + a // 4  # Gregorian calendar; every epoch here is post-1582.
    return (
        int(365.25 * (year + 4716))
        + int(30.6001 * (month + 1))
        + day
        + b
        - 1524.5
    )


def _horizons(params: dict[str, str]) -> tuple[str, str]:
    query = urllib.parse.urlencode(params, quote_via=urllib.parse.quote)
    url = f"{HORIZONS_API}?{query}"
    with urllib.request.urlopen(url, timeout=120) as response:
        body = response.read().decode("utf-8", errors="replace")
    if body.lstrip().startswith("API ERROR") or "$$SOE" not in body or "$$EOE" not in body:
        raise SystemExit(
            f"Horizons request failed (no ephemeris block in the response).\nURL: {url}\n"
            f"--- response head ---\n{body[:800]}"
        )
    return url, body


def _rows(body: str) -> list[str]:
    block = body.split("$$SOE", 1)[1].split("$$EOE", 1)[0]
    return [line for line in block.splitlines() if line.strip()]


def fetch_tropical_longitudes(
    target: str, julian_days: list[float]
) -> tuple[str, dict[float, float]]:
    """Apparent geocentric ecliptic longitude of date, keyed by UT Julian Day."""
    url, body = _horizons(
        {
            "format": "text",
            "COMMAND": f"'{target}'",
            "OBJ_DATA": "'NO'",
            "MAKE_EPHEM": "'YES'",
            "EPHEM_TYPE": "'OBSERVER'",
            "CENTER": f"'{GEOCENTRE}'",
            "QUANTITIES": "'31'",
            "TLIST": " ".join(f"{jd:.9f}" for jd in julian_days),
            "TLIST_TYPE": "'JD'",
            "TIME_TYPE": "'UT'",
            "CAL_FORMAT": "'JD'",
        }
    )
    values: dict[float, float] = {}
    for row in _rows(body):
        fields = row.split()
        if len(fields) < 3:
            raise SystemExit(f"unparsable Horizons observer row: {row!r}")
        values[round(float(fields[0]), 9)] = float(fields[1])
    if len(values) != len(julian_days):
        raise SystemExit(
            f"Horizons returned {len(values)} rows for {len(julian_days)} requested "
            f"times (target {target}) — refusing to record a partial corpus.\nURL: {url}"
        )
    return url, values


def fetch_moon_osculating_nodes(
    julian_days_tdb: list[float],
) -> tuple[str, dict[float, float]]:
    """Longitude of the Moon's osculating ascending node, ecliptic of J2000.0."""
    url, body = _horizons(
        {
            "format": "text",
            "COMMAND": f"'{MOON_TARGET}'",
            "OBJ_DATA": "'NO'",
            "MAKE_EPHEM": "'YES'",
            "EPHEM_TYPE": "'ELEMENTS'",
            "CENTER": f"'{GEOCENTRE}'",
            "REF_PLANE": "'ECLIPTIC'",
            "TLIST": " ".join(f"{jd:.9f}" for jd in julian_days_tdb),
            "TLIST_TYPE": "'JD'",
        }
    )
    if "Ecliptic of J2000.0" not in body:
        raise SystemExit(
            "Horizons did not report 'Reference frame : Ecliptic of J2000.0' for the "
            "osculating elements. The frame this corpus assumes has changed; do NOT "
            f"record. URL: {url}"
        )
    values: dict[float, float] = {}
    current_jd: float | None = None
    for row in _rows(body):
        stripped = row.strip()
        header = re.match(r"^(\d+\.\d+)\s*=", stripped)
        if header:
            current_jd = round(float(header.group(1)), 9)
            continue
        node = re.search(r"\bOM\s*=\s*([-\d.E+]+)", stripped)
        if node and current_jd is not None:
            values[current_jd] = float(node.group(1)) % 360.0
    if len(values) != len(julian_days_tdb):
        raise SystemExit(
            f"Horizons returned {len(values)} element sets for "
            f"{len(julian_days_tdb)} requested times — refusing to record a partial "
            f"corpus.\nURL: {url}"
        )
    return url, values


def build() -> dict:
    # swisseph is used for exactly two things here, neither of which is an expected
    # value: (a) Delta-T, to name the TDB instant that corresponds to each UT epoch,
    # and (b) the engine's own ayanamsa, recorded as a NON-independent field. Both
    # sides of the node comparison then use the SAME TDB instant, so Delta-T cancels
    # out of the assertion entirely rather than entering it as an error term.
    sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))
    import swisseph as swe  # noqa: E402
    from jhora.panchanga import drik  # noqa: E402

    from bphs_core import utils  # noqa: E402

    utils._ensure_thread_ephemeris_state()

    epochs: list[dict] = []
    for epoch in EPOCHS:
        jd_ut = _julian_day_ut(epoch["utc"])
        delta_t_days = swe.deltat(jd_ut)
        epochs.append(
            {
                **epoch,
                "jd_ut": round(jd_ut, 9),
                "jd_tdb": round(jd_ut + delta_t_days, 9),
                "delta_t_seconds": round(delta_t_days * 86400.0, 6),
            }
        )

    ut_days = [epoch["jd_ut"] for epoch in epochs]
    tdb_days = [epoch["jd_tdb"] for epoch in epochs]

    queries: dict[str, str] = {}
    tropical: dict[str, dict[float, float]] = {}
    for graha in VISIBLE_GRAHAS:
        url, values = fetch_tropical_longitudes(HORIZONS_TARGET[graha], ut_days)
        queries[f"tropical_apparent_longitude_deg.{graha}"] = url
        tropical[graha] = values
        print(f"  fetched {graha:<8} ({len(values)} epochs)")

    node_url, nodes = fetch_moon_osculating_nodes(tdb_days)
    queries["moon_osculating_node_j2000_deg"] = node_url
    print(f"  fetched Moon osculating node ({len(nodes)} epochs)")

    for epoch in epochs:
        epoch["tropical_apparent_longitude_deg"] = {
            graha: tropical[graha][epoch["jd_ut"]] for graha in VISIBLE_GRAHAS
        }
        epoch["moon_osculating_node_j2000_deg"] = nodes[epoch["jd_tdb"]]
        epoch["ayanamsa_deg"] = round(drik.get_ayanamsa_value(epoch["jd_ut"]), 9)

    return {
        "schema_version": 1,
        "provenance": {
            "recorded_utc": datetime.datetime.now(datetime.timezone.utc)
            .replace(microsecond=0)
            .isoformat()
            .replace("+00:00", "Z"),
            "recorder": "ci/fetch_reference_corpus.py",
            "fields": {
                "tropical_apparent_longitude_deg": {
                    "source": "NASA/JPL Horizons",
                    "independent_of_this_engine": True,
                    "what": "Apparent geocentric ecliptic longitude referred to the "
                            "ecliptic and TRUE equinox of date, observer at the "
                            "geocentre (500@399), Horizons observer QUANTITIES='31' "
                            "(ObsEcLon). Includes light-time, aberration, relativistic "
                            "deflection and nutation, matching swisseph's default "
                            "apparent position.",
                },
                "moon_osculating_node_j2000_deg": {
                    "source": "NASA/JPL Horizons",
                    "independent_of_this_engine": True,
                    "what": "Longitude of the ascending node (OM) of the Moon's "
                            "osculating orbit about the Earth, referred to the "
                            "ECLIPTIC OF J2000.0, from Horizons EPHEM_TYPE='ELEMENTS' "
                            "at the epoch's jd_tdb. This is the independent expected "
                            "value for the declared lunar node model.",
                },
                "ayanamsa_deg": {
                    "source": "engine",
                    "independent_of_this_engine": False,
                    "what": "The Lahiri ayanamsa this engine computes. Recorded so the "
                            "sidereal->tropical composition can be checked against "
                            "Horizons, NOT as an independently-sourced expected value: "
                            "the sidereal zero point is an astrological convention "
                            "(Indian Calendar Reform Committee) with no counterpart in "
                            "any solar-system ephemeris. Pinning it to a published "
                            "authority is tracked as follow-up work.",
                },
                "jd_ut": {
                    "source": "ci/fetch_reference_corpus.py",
                    "independent_of_this_engine": True,
                    "what": "UT Julian Day by the textbook civil-calendar conversion "
                            "(Meeus ch. 7), deliberately not swisseph's swe.julday.",
                },
                "jd_tdb": {
                    "source": "engine (Delta-T only)",
                    "independent_of_this_engine": False,
                    "what": "jd_ut + swe.deltat(jd_ut). Names WHICH TDB instant the "
                            "node was requested at; both sides of the node assertion "
                            "use this same instant, so Delta-T cancels out of the "
                            "comparison instead of entering it as an error term.",
                },
            },
            "horizons_queries": queries,
        },
        "epochs": epochs,
    }


def canonical(document: dict) -> str:
    return json.dumps(document, indent=2, sort_keys=True) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fetch and report drift against the committed corpus; write nothing",
    )
    arguments = parser.parse_args()

    print(f"fetching the independent reference corpus from {HORIZONS_API}")
    document = build()

    if arguments.check:
        if not CORPUS_PATH.is_file():
            print(f"no committed corpus at {CORPUS_PATH}", file=sys.stderr)
            return 1
        committed = json.loads(CORPUS_PATH.read_text(encoding="utf-8"))
        drifted = False
        for fresh, old in zip(document["epochs"], committed["epochs"]):
            for graha, value in fresh["tropical_apparent_longitude_deg"].items():
                delta = abs(value - old["tropical_apparent_longitude_deg"][graha]) * 3600.0
                if delta > 1e-3:
                    drifted = True
                    print(f"DRIFT {fresh['id']}.{graha}: {delta:.6f} arcsec")
            delta = abs(fresh["moon_osculating_node_j2000_deg"] - old["moon_osculating_node_j2000_deg"]) * 3600.0
            if delta > 1e-3:
                drifted = True
                print(f"DRIFT {fresh['id']}.node: {delta:.6f} arcsec")
        print("corpus matches Horizons" if not drifted else "corpus has DRIFTED")
        return 1 if drifted else 0

    CORPUS_PATH.parent.mkdir(parents=True, exist_ok=True)
    CORPUS_PATH.write_text(canonical(document), encoding="utf-8", newline="\n")
    print(f"wrote {CORPUS_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
